
name: Update language data

on:
  schedule:
  - cron: "45 16 * * *"

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download file
      run: wget http://download.geonames.org/export/dump/iso-languagecodes.txt -o data/languages.txt
    
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    
    - name: Commit update
      if: steps.changes.outputs.changed == 1
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Ashley Clarke
        author_email: me@ashleyclarke.me
        message: "Updated languages"
        add: "data/languages.txt"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Release
      if: steps.changes.outputs.changed == 1
      uses: craig-day/compute-tag@v10
      with:
        github_token: ${{ github.token }}
